/* Native Hub reporting regression, with local fake-provider fixtures only. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {spawn}=require('node:child_process'),{chromium}=require('playwright'),{AxeBuilder}=require('@axe-core/playwright');
const root=path.resolve(__dirname,'../..'),output=process.env.UI_OUTPUT||'/tmp/swangz-hub-ui';fs.mkdirSync(output,{recursive:true});
let fixture,browser;const results={screens:[],errors:[],failedRequests:[],actions:[]};
async function start(){fixture=spawn('python3',[path.join(__dirname,'demo.py')],{cwd:root,env:{...process.env,HUB_UI_FIXTURE:'1'},stdio:['ignore','pipe','pipe']});return new Promise((resolve,reject)=>{let out='',err='';const t=setTimeout(()=>reject(Error('Fixture timeout '+err)),30000);fixture.stderr.on('data',d=>err+=d);fixture.stdout.on('data',d=>{out+=d;if(out.includes('\n')){clearTimeout(t);resolve(JSON.parse(out.split('\n')[0]));}});fixture.on('exit',()=>{clearTimeout(t);reject(Error(err));});});}
async function view(p,url,route,text){await p.goto(url+route);await p.getByRole('heading',{name:text,exact:true}).first().waitFor();await p.waitForFunction(()=>!document.querySelector('main .u-skel-rows'));await p.waitForTimeout(150);}
async function screen(p,name){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow');const violations=(await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;results.screens.push({name,violations:violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))});await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});assert.deepEqual(violations.map(v=>v.id),[],name+' accessibility');}
(async()=>{const {url,reports}=await start();assert.equal(reports.length,2);browser=await chromium.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox']});const staff=await browser.newContext(),admin=await browser.newContext();
assert.equal((await staff.request.post(url+'/api/login',{headers:{'x-swangz-app':'1'},data:{email:'grace@swangzavenue.com',password:'demo-password'}})).status(),200);
assert.equal((await admin.request.post(url+'/admin/api/login',{headers:{'x-gateway-admin':'1'},data:{username:'owner@swangzavenue.com',password:'owner-password'}})).status(),200);
const p=await staff.newPage(),a=await admin.newPage();for(const page of [p,a]){page.on('pageerror',e=>results.errors.push(e.message));page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)results.failedRequests.push({url:r.url(),status:r.status()});});}
for(const theme of (process.env.HUB_UI_FAST?['dark']:['dark','light']))for(const width of (process.env.HUB_UI_FAST?[1440]:[1440,768,390])){for(const page of [p,a]){await page.setViewportSize({width,height:900});await page.addInitScript(t=>localStorage.setItem('swangz-theme',t),theme);}
 await view(p,url,'/#/weekly?report='+reports[0],'Confirm usage');await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);if(width>900){assert.ok(await p.locator('.hub-staff-nav svg').evaluateAll(nodes=>nodes.every(n=>n.getBoundingClientRect().width<=20&&n.getBoundingClientRect().height<=20)),'Compact sidebar icons');assert.ok(await p.locator('.hub-staff-side').evaluate(n=>n.scrollHeight<=n.clientHeight),'All desktop navigation fits');}await screen(p,theme+'-'+width+'-wizard');
 await view(a,url,'/admin#/weekly?tab=all','Weekly reporting');await a.evaluate(t=>document.documentElement.dataset.theme=t,theme);await a.getByRole('table').first().waitFor();await screen(a,theme+'-'+width+'-admin');
}
await p.setViewportSize({width:1440,height:900});await view(p,url,'/#/weekly?report='+reports[0],'Confirm usage');await p.getByRole('button',{name:'Save draft',exact:true}).click();await p.waitForTimeout(150);assert.equal(await p.locator('.hub-wizard .form-error').innerText(),'');await p.getByLabel('Did you use this tool?').selectOption('used');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByLabel('Business problem and purpose').fill('Campaign research');await p.getByRole('button',{name:'Save draft',exact:true}).click();await p.waitForTimeout(250);await p.reload();await p.getByLabel('Business problem and purpose').waitFor();assert.equal(await p.getByLabel('Business problem and purpose').inputValue(),'Campaign research');
await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByLabel('Business impact').fill('A clearer proposal');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByLabel('Manual work hours').fill('4');await p.getByLabel('AI-assisted work hours').fill('1');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByRole('button',{name:'Submit report',exact:true}).click();await p.getByText('This report is submitted. Its reporting requirement is cleared.').waitFor();results.actions.push('Six-step draft persistence, refresh, submission and immediate gate clearance');
const submitted=await (await staff.request.get(url+'/api/hub/reports/'+reports[0])).json();assert.equal(submitted.state,'submitted');assert.equal(submitted.versions.length,1);
await view(a,url,'/admin#/weekly?tab=all&report='+reports[0]+'&detail=review','Weekly reporting');await a.getByLabel('Review note').waitFor();await screen(a,'report-review-drawer');await a.getByLabel('Review note').fill('Please clarify the project.');await a.getByRole('button',{name:'Returned for correction',exact:true}).click();await a.waitForTimeout(200);assert.equal((await (await staff.request.get(url+'/api/hub/reports/'+reports[0])).json()).state,'returned');results.actions.push('Auditable return for correction');
await view(p,url,'/#/requests?view=procurement','Requests');await p.getByText('Propose a tool, subscription or credits',{exact:true}).click();await p.getByLabel('Tool name').fill('Hub test tool');await p.getByLabel('Purchase type').selectOption('credits');await p.getByLabel('Business reason').fill('Approved production work');await p.getByRole('button',{name:'Submit procurement request'}).click();await p.getByRole('cell',{name:'Hub test tool',exact:true}).waitFor();results.actions.push('Native procurement flow');
const buys=await(await staff.request.get(url+'/api/hub/procurement')).json();await view(a,url,'/admin#/procurement?request='+buys.items[0].id,'Tool & subscription requests');await a.getByRole('dialog',{name:'Procurement request',exact:true}).waitFor();await a.reload();await a.getByRole('dialog',{name:'Procurement request',exact:true}).waitFor();await screen(a,'procurement-detail-drawer');await a.getByRole('button',{name:'Close procurement'}).click();assert.ok(!a.url().includes('request='));results.actions.push('Procurement drawer deep link and refresh');
for(const tab of ['overview','staff','tools','reconciliation','review','adoption','analytics','policy']){await view(a,url,'/admin#/weekly?tab='+tab,'Weekly reporting');await a.waitForLoadState('networkidle');assert.equal(await a.locator('main').getByText('[object Promise]',{exact:true}).count(),0);assert.equal(await a.locator('main .u-state.bad').count(),0);results.actions.push('Admin reporting tab '+tab);}
await view(a,url,'/admin#/weekly?tab=analytics&section=observed','Weekly reporting');await a.waitForLoadState('networkidle');await a.getByRole('table').first().waitFor();await screen(a,'management-observations');await a.getByRole('tab',{name:'Staff estimates',exact:true}).click();await a.getByRole('table').first().waitFor();await screen(a,'management-staff-estimates');
await view(p,url,'/#/activity','My activity');await screen(p,'staff-activity');
await view(p,url,'/#/weekly?view=completed','Weekly reports');await p.reload();await p.getByRole('tab',{name:'Submitted',exact:true}).waitFor();assert.equal(await p.getByRole('tab',{name:'Submitted',exact:true}).getAttribute('aria-selected'),'true');await p.getByRole('tab',{name:'Pending & returned'}).click();await p.goBack();assert.match(p.url(),/view=completed/);results.actions.push('Tab deep link, refresh and Back');assert.deepEqual(results.errors,[]);assert.deepEqual(results.failedRequests,[]);console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));await browser?.close();fixture?.kill('SIGTERM');});
